### ISSUE TITLE
 tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by munib94** [xingyul/flownet3d#41]
Hi,

I installed TensorFlow and tried executing `sh command_train.sh` but I ended up getting the following error:

    Traceback (most recent call last):
      File "train.py", line 49, in <module>
        MODEL = importlib.import_module(FLAGS.model) # import network module
      File "/home/workstation/.pyenv/versions/anaconda3- 
    5.0.0/envs/rangenet++/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/workstation/Documents/flownet3d/model_concat_upsa.py", line 13, in <module>
        from pointnet_util import *
      File "/home/workstation/Documents/flownet3d/utils/pointnet_util.py", line 16, in <module>
        from tf_sampling import farthest_point_sample, gather_point
      File "/home/workstation/Documents/flownet3d/tf_ops/sampling/tf_sampling.py", line 12, in 
    <module>
        sampling_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_sampling_so.so'))
      File "/home/workstation/.pyenv/versions/anaconda3-5.0.0/envs/rangenet++/lib/python3.6/site- 
    packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
        None, None, error_msg, error_code)
    tensorflow.python.framework.errors_impl.NotFoundError: 
    /home/workstation/Documents/flownet3d/tf_ops/sampling/tf_sampling_so.so: cannot open 
    shared object file: No such file or directory

How do I fix this error?

**Comment by xingyul** [comment]
You will first need to compile the Tensorflow ops. Please follow the instructions in README.
