### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by munib94** [xingyul/flownet3d#42]
Hi,

After installing the requirements described in the README (tensorflow-gpu 1.9.0, g++ 5.4.0, CUDA 9.0 and Python 3.5 on Ubuntu 16.04), I was able to compile successfully. However, when I execute `sh command_train.sh`, I encounter the following error:

    Traceback (most recent call last):
      File "train.py", line 49, in <module>
        MODEL = importlib.import_module(FLAGS.model) # import network module
      File "/home/workstation/.pyenv/versions/anaconda3- 
    5.0.0/envs/flownet3d/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 985, in _gcd_import
      File "<frozen importlib._bootstrap>", line 968, in _find_and_load
      File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 697, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/home/workstation/Documents/flownet3d/model_concat_upsa.py", line 13, in <module>
        from pointnet_util import *
      File "/home/workstation/Documents/flownet3d/utils/pointnet_util.py", line 16, in <module>
        from tf_sampling import farthest_point_sample, gather_point
      File "/home/workstation/Documents/flownet3d/tf_ops/sampling/tf_sampling.py", line 12, in 
    <module>
        sampling_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_sampling_so.so'))
      File "/home/workstation/.pyenv/versions/anaconda3-5.0.0/envs/flownet3d/lib/python3.5/site-        
    packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
        lib_handle = py_tf.TF_LoadLibrary(library_filename)
    tensorflow.python.framework.errors_impl.NotFoundError:     
    /home/workstation/Documents/flownet3d/tf_ops/sampling/tf_sampling_so.so: undefined symbol:     
    _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

I am not sure what went wrong. Any explanation as to why this is happening and how to solve the issue would be much appreciated.

**Comment by munib94** [comment]
Solved it according to https://github.com/xingyul/flownet3d/issues/2. Additionally had to delete my local repo and re-clone the project.
