### ISSUE TITLE
Segmentation Fault when running kitti usage example

### ISSUE THREAD

**Issue by GMNetto** [xingyul/flownet3d#48]
Hi,

Following the Kitti experiment I get a segmentation fault when the evaluate.py gets to the function https://github.com/xingyul/flownet3d/blob/master/tf_ops/sampling/tf_sampling.py#L29 . I am not sure what could be causing the issue as I got to compile with no problems the code previously. I am running on ubuntu 18.04, Cuda 9.1 and Tensorflow 1.14.

Thanks.

**Comment by xingyul** [comment]
What GPU are you using? It's likely that you didn't change the `arch` in Makefiles. Please see instructions [here](https://github.com/xingyul/flownet3d#compile-customized-tf-operators).

**Comment by GMNetto** [comment]
Hi, actually the arch is correct, the GPU I am using is `GeForce GTX 1070` which matches the sm_61 I am compiling with. I got to retrain the model on a dockerfile with cuda 9.0 and tensorflow 1.9.0, this lead me to run as expected the fying things evaluate script. However, When trying to run the kitti evaluation, after download the pre-processed kitti data I am getting:
```
2020-04-06 22:11:19.184010: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-06 22:11:19.186401: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2020-04-06 22:11:19.186440: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: 39d390f0741d
2020-04-06 22:11:19.186449: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: 39d390f0741d
2020-04-06 22:11:19.186479: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 430.50.0
2020-04-06 22:11:19.186499: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 430.50.0
2020-04-06 22:11:19.186508: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 430.50.0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1305, in _run_fn
    self._extend_graph()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1340, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'FarthestPointSample' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'
```

**Comment by GMNetto** [comment]
Hi, actually after I retrained the model I was able to run the example.
